---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: &name postgres18-immich
spec:
  instances: 3
  # renovate: datasource=docker depName=ghcr.io/tensorchord/cloudnative-vectorchord versioning=loose enabled=false
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:18.1
  primaryUpdateStrategy: unsupervised
  storage:
    size: 10Gi
    storageClass: ceph-block
  superuserSecret:
    name: cloudnative-pg
  enableSuperuserAccess: true
  postgresql:
    shared_preload_libraries:
      - "vchord.so"
    parameters:
      max_connections: "400"
      shared_buffers: 256MB

  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
    podAntiAffinityType: required

  resources:
    requests:
      cpu: 100m
    limits:
      memory: 2Gi
  monitoring:
    enablePodMonitor: true

  backup:
    retentionPolicy: 14d
    volumeSnapshot:
      className: csi-ceph-blockpool
      snapshotOwnerReference: cluster
  plugins:
    - enabled: true
      isWALArchiver: true
      name: barman-cloud.cloudnative-pg.io
      parameters:
        barmanObjectName: minio
        serverName: postgres18-immich-v3

  #bootstrap:
  #  initdb:
  #    import:
  #      type: monolith
  #      databases:
  #        - 'immich'
  #      roles:
  #        - '*'
  #      source:
  #        externalCluster: &previousCluster postgres16-immich-restore

  #externalClusters:
  #   - name: *previousCluster
  #     connectionParameters:
  #       host: postgres16-immich-restore-rw
  #       user: postgres
  #       dbname: postgres
  #     password:
  #       name: cloudnative-pg
  #       key: password
