---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: &name postgres18-immich
spec:
  instances: 3
  # Immich v2.3.1 requires VectorChord >=0.3 <0.6
  # renovate: datasource=docker depName=ghcr.io/tensorchord/cloudnative-vectorchord versioning=loose enabled=false
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:18.0-0.5.3@sha256:267f6cbb32af6e109e138a143c7e9dd5d44d68433ec2303f0c30e745c788d1a9
  primaryUpdateStrategy: unsupervised
  storage:
    size: 10Gi
    storageClass: ceph-block
  superuserSecret:
    name: cloudnative-pg
  enableSuperuserAccess: true
  postgresql:
    shared_preload_libraries: ["vchord.so"]
    parameters:
      shared_buffers: 256MB
      max_connections: "400"
  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
    podAntiAffinityType: required
  resources:
    requests:
      cpu: 100m
    limits:
      memory: 2Gi
  monitoring:
    enablePodMonitor: true

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: minio
        serverName: postgres18-immich-v1

  bootstrap:
    initdb:
      database: immich
      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS vchord CASCADE
        - CREATE EXTENSION IF NOT EXISTS vector CASCADE
        - CREATE EXTENSION IF NOT EXISTS earthdistance CASCADE
