---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: database
resources:
  - ./cluster18.yaml
  - ./cluster18-immich.yaml
  - ./objectstore.yaml
  - ./objectstore-garage.yaml
  - ./scheduledbackup.yaml
  - ./prometheusrule.yaml
