---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: postgres18
  namespace: database
spec:
  schedule: "@daily"
  immediate: true
  backupOwnerReference: self
  cluster:
    name: postgres18
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io

---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: postgres18-immich
  namespace: database
spec:
  schedule: "@daily"
  immediate: true
  backupOwnerReference: self
  cluster:
    name: postgres18-immich
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
