---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app garage
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 1h
  target:
    name: *app
    template:
      data:
        GARAGE_RPC_SECRET: "{{ .RPC_SECRET }}"
        GARAGE_ADMIN_TOKEN: "{{ .ADMIN_TOKEN }}"
        GARAGE_METRICS_TOKEN: "{{ .METRICS_TOKEN }}"
  dataFrom:
  - extract:
      key: *app
