---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./deployment.yaml
  - ./service.yaml
configMapGenerator:
  - name: ntfy-bridge-code
    files:
      - app.py
generatorOptions:
  disableNameSuffixHash: true
