---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app frigate
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 1h
  target:
    name: *app
    template:
      engineVersion: v2
      data:
        FRIGATE_DOMAIN: "{{ .FRIGATE_DOMAIN }}"
        FRIGATE_RTSP_PASSWORD: "{{ .FRIGATE_RTSP_PASSWORD }}"
        FRIGATE_DOORBELL_PASSWORD: "{{ .FRIGATE_DOORBELL_PASSWORD }}"
        PLUS_API_KEY: "{{ .FRIGATE_API_KEY }}"
  dataFrom:
  - extract:
      key: *app
