---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app cliparr
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 1h
  target:
    name: *app
    template:
      engineVersion: v2
      data:
        APP_KEY: "{{ .APP_KEY }}"
  dataFrom:
    - extract:
        key: *app
