---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app alloy
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: alloy
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    fullnameOverride: alloy
    serviceMonitor:
      enabled: true
    alloy:
      configMap:
        create: false
        name: *app
        key: config.alloy
    controller:
      podAnnotations:
        configmap.reloader.stakater.com/reload: *app
