---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app immich
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 1h
  target:
    name: *app
    template:
      data:
        # Immich
        DB_DATABASE_NAME: &dbName immich
        DB_HOSTNAME: &dbHost postgres18-immich-rw.database.svc.cluster.local
        DB_USERNAME: &dbUser '{{ .DBUSER }}'
        DB_PASSWORD: &dbPass '{{ .DBPASS }}'
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: '{{ .postgres_pw }}'
  dataFrom:
    - extract:
        key: immich
    - extract:
        key: postgres-superuser
