---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app technitium-dns-companion
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 1h
  target:
    name: *app
    template:
      data:
        TECHNITIUM_BACKGROUND_TOKEN: "{{ .BACKGROUND_TOKEN }}"
        TECHNITIUM_PRIMARY_BASE_URL: "{{ .PRIMARY_BASE_URL }}"
        TECHNITIUM_SECONDARY_BASE_URL: "{{ .SECONDARY_BASE_URL }}"
  dataFrom:
  - extract:
      key: *app
