apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  TZ: ENC[AES256_GCM,data:6JW329AzyRK3chA9/bWO7A==,iv:Dw+urHH32MpI6ot3srjMM81Xxjmj1fEUV+uucol9gNk=,tag:b7eDWz2aittFAbCSHyEcpQ==,type:str]
  SECRET_DOMAIN: ENC[AES256_GCM,data:+u4qwXdZ3K8=,iv:BGDcLO5q7T/diNEG2QI492CWaqCYCAXwMJlH2NqnH4U=,tag:Vmi+H6na/GuQCR1BxvyiBg==,type:str]
  SECRET_OG_DOMAIN: ENC[AES256_GCM,data:6gzfZGBqOQ==,iv:SWlBNVWIUl7nyj4LhxwjpemcAatwsCitY7uMovgwGZE=,tag:yEckuUloh0MbxGF/n/ZD8w==,type:str]
  SECRET_DNS_SERVER: ENC[AES256_GCM,data:eALrNUwgLP0p1A==,iv:jNoaFYfO2WVuDolCBEN+FNK5czxuMVKmqoAwLUJ3dyw=,tag:R0hp+ob5dIANA1eBIy4s6Q==,type:str]
  SECRET_DNS_SERVER2: ENC[AES256_GCM,data:40ZRj0Fj97SLaWY=,iv:R+QQ73z7OksvJ87yFVR+HpFd91+T8HlxBUTKGxxZ9ro=,tag:LFc0R591AbC0ICLbsi5Veg==,type:str]
  SECRET_NFS_SERVER: ENC[AES256_GCM,data:fhqfCOSSM4/395o1,iv:bkXeNwehAQANVmknfSUJno+jeTQjnlroN9zKv/Re6ls=,tag:M3lK8aEEzHgw57jL7tCZ5A==,type:str]
  SVC_MOSQUITTO_ADDR: ENC[AES256_GCM,data:uS2DMSQnbDt2PjU=,iv:LYlvFGmrCGZ9w2MLfYNFejk5gvFvmqXx+E3aZQZc/D0=,tag:8MaQgalOgIn83gZwefmjDw==,type:str]
sops:
  age:
    - recipient: age1e0zlhyhj8qsh4u82u30tsr2n5a2x6na3genefr068jw3s4w0ae4qwc9xd4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzczEwVFpFT05hNWJxNUhx
        RFErUkNScktRV2UzbGpielFCSnJzV2prUlJrCmdMS1M2dEJGN0JFS2JrbWdzL3Ju
        c2FIWko3SXgxUFdsRjZwdTUrZHBjcVUKLS0tIFg1OGJleTRjaGxhQTIyYlhXOVUw
        VW1IWm14a2xXUUJZcmFNVncyRWxTeFUKE4F4SB6Fwv/lLf+CqAjXrVDmDb1OGtfb
        AYn+Zwazb6OPsXde+CqK+lXdAGroibJHjjZw8UNPQ3/SC4EStVeiDA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-23T04:31:51Z"
  mac: ENC[AES256_GCM,data:6yfPj7HL7TozjyWL5sV/Ox77py2wm23NDkNFEtMbbq1NtZc9BCb61tOn104Uih4+O2nWSVtWFcEF4F31mNFOdgh8trwn7KkMNRIM+3qSskZ22bP0i83NzMYgr9n/0FGEMvycVSWtbCDzX0wKqPLUTcRLU6Wcj+TYm0zU3go9Wyg=,iv:tUtrykImFIWXKtHAr6fzTiXpXs/96/L4RRXAtmCwBO4=,tag:Ho9ftGxptwhMpmep6oFE4Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
