---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: telegram
  namespace: flux-system
spec:
  type: generic
  address: http://telegram-bridge.flux-system.svc.cluster.local:8080/
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: telegram-alert
  namespace: flux-system
spec:
  providerRef:
    name: telegram
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: '*'
  exclusionList:
    - ".*Dependencies do not meet ready condition.*"
    - ".*Reconciliation finished in .*$"
