apiVersion: v1
kind: Secret
metadata:
  name: telegram-secret
  namespace: flux-system
stringData:
  token: ENC[AES256_GCM,data:Zf0tTG9n/3drkPxsPH/gpLY4BWJXJ7izdRdSxdcV8Gr/OX4bw0LR7Jq+YJBJpQ==,iv:9CkgCqDEs7yI9C4WoTtZoz3ap3gX3JTnBG9DCruauHw=,tag:W89qu9ojd/vE6VXXusEFnA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLTkFocGduWUVNYzhxZWZM
        S1FOQnQ2SUs3S1IrdmJITUlWbzhTWW9VSDBFCllCSTQ1NGxRWjB3YnROUS9OU3ZH
        RzFEVFBvUFhkN2V4QlFtZnBtSU1ZT2sKLS0tIFptMlNDWTNTeTUydmUrVDZxdWdE
        a1FUWnZOQnJCZGhkeGJLMUZMUDVmbWMKBzQIfM/oa52zY1Kg2PukpMR571/bbRQE
        tv6yWVByitW5iBf28B3Z/LzHoG2RhBXbUSRc+SkUYLI4tWYC2Xo14w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e0zlhyhj8qsh4u82u30tsr2n5a2x6na3genefr068jw3s4w0ae4qwc9xd4
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-14T20:27:41Z"
  mac: ENC[AES256_GCM,data:yKhKT9G0GvyvEpX5Zpi8ySY+GfnzpbtX45D6Ad6siXvJN+8C8YDht7MQDGN6uF/L0DnyYmVf1i9K8mOwrG3jce4jh2PrNf3ckM8Re1InbUITD3kANFtwUiPDFMgKP/ezCBCwPT0YxEHNvELJnShANlZl42K0zA1gt9HweCFfQ8M=,iv:ktA9iKLHWSlJI505UKdms1ybNniuPwMd+VTZ8H9lJTk=,tag:6miLih0HEh1m0KoM706e4w==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
