---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: telegram
  namespace: flux-system
spec:
  type: telegram
  channel: "5225713334"
  secretRef:
    name: telegram-secret
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: telegram-alert
  namespace: flux-system
spec:
  providerRef:
    name: telegram
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: '*'
  exclusionList:
    - ".*Dependencies do not meet ready condition.*"
