---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app kopia-maintenance
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 1h
  target:
    name: *app
    template:
      engineVersion: v2
      data:
        KOPIA_PASSWORD: "{{ .password }}"
        KOPIA_FS_PATH: /repository
        KOPIA_REPOSITORY: filesystem:///repository
  dataFrom:
  - extract:
      key: kopia


