---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/kopiamaintenance_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: KopiaMaintenance
metadata:
  name: daily
  namespace: storage
spec:
  enabled: true
  trigger:
    schedule: 23 * * * *
  repository:
    repository: kopia-maintenance
  podSecurityContext:
    runAsUser: 568
    runAsGroup: 568
    fsGroup: 568
  moverVolumes:
    - mountPath: repository
      volumeSource:
        nfs:
          server: ${SECRET_NFS_SERVER}
          path: /spinnerpool/backup/VolsyncKopia
