---
apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-configmap
data:
  IMMICH_WEB_URL: http://immich-web.media:3000
  IMMICH_SERVER_URL: http://immich-server.media:3001
  PUBLIC_IMMICH_SERVER_URL: https://images.${SECRET_OG_DOMAIN}
  DB_PORT: "5432"
  REDIS_HOSTNAME: dragonfly.database.svc.cluster.local
  REDIS_PORT: "6379"
