apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: restore-radarr
  namespace: media
spec:
  trigger:
    manual: restore-once
  kopia:
    repository: radarr-volsync-secret
    cacheStorageClassName: ceph-block
    capacity: 1Gi
    copyMethod: Snapshot
    moverSecurityContext:
      fsGroup: 568
      runAsGroup: 568
      runAsUser: 568
    sourceIdentity:
      sourceName: migrate-radarr
      sourceNamespace: media
    destinationPVC: radarr
    storageClassName: ceph-block
    accessModes:
      - ReadWriteOnce
    # Cleanup
    cleanupCachePVC: true
    cleanupTempPVC: true
    volumeSnapshotClassName: ceph-block
