apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: restore-silverbullet
  namespace: default
spec:
  trigger:
    manual: restore-once
  kopia:
    repository: silverbullet-volsync-secret
    cacheStorageClassName: ceph-block
    cacheCapacity: 1Gi
    copyMethod: Snapshot
    moverSecurityContext:
      fsGroup: 568
      runAsGroup: 568
      runAsUser: 568
    sourceIdentity:
      sourceName: migrate-silverbullet
      sourceNamespace: default
    destinationPVC: silverbullet
    storageClassName: ceph-block
    accessModes:
      - ReadWriteOnce
    # Cleanup
    cleanupCachePVC: true
    cleanupTempPVC: true
    volumeSnapshotClassName: ceph-block
