---
apiVersion: batch/v1
kind: Job
metadata:
  name: forgejo-db-init
  namespace: dev
spec:
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: init-db
          image: ghcr.io/home-operations/postgres-init:18
          envFrom:
            - secretRef:
                name: forgejo-secret
