---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 1h
  target:
    name: forgejo-secret
    template:
      data:
        DB_PASSWORD: '{{ .DBPASS }}'
        token: '{{ .RUNNER_TOKEN }}'
        INIT_POSTGRES_DBNAME: forgejo
        INIT_POSTGRES_HOST: postgres18-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: forgejo
        INIT_POSTGRES_PASS: '{{ .DBPASS }}'
        INIT_POSTGRES_SUPER_PASS: '{{ .postgres_pw }}'
  dataFrom:
    - extract:
        key: forgejo
    - extract:
        key: postgres-superuser
