---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo
spec:
  chartRef:
    kind: OCIRepository
    name: forgejo
  interval: 1h
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: forgejo
            patch: |
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: forgejo
              spec:
                template:
                  spec:
                    initContainers:
                      - name: init-db
                        image: ghcr.io/home-operations/postgres-init:18
                        envFrom:
                          - secretRef:
                              name: forgejo-secret
  valuesFrom:
    - kind: Secret
      name: forgejo-secret
      valuesKey: DB_PASSWORD
      targetPath: gitea.config.database.PASSWD
  values:
    gitea:
      admin:
        username: ""
      config:
        database:
          DB_TYPE: postgres
          HOST: postgres18-rw.database.svc.cluster.local:5432
          NAME: forgejo
          USER: forgejo
        cache:
          ADAPTER: memory
        server:
          ROOT_URL: https://git.${SECRET_DOMAIN}
          SSH_DOMAIN: git.${SECRET_DOMAIN}
          SSH_PORT: &sshPort 22
        service:
          DISABLE_REGISTRATION: false
          ALLOW_ONLY_EXTERNAL_REGISTRATION: false
          SHOW_REGISTRATION_BUTTON: true
        webhook:
          ALLOWED_HOST_LIST: "*"
    image:
      rootless: true
      registry: code.forgejo.org
      repository: forgejo/forgejo
      tag: 16.0.5-rootless
    persistence:
      enabled: true
    postgresql:
      enabled: false
    postgresql-ha:
      enabled: false
    redis-cluster:
      enabled: false
    service:
      http:
        port: 3000
      ssh:
        type: ClusterIP
        port: *sshPort
    httpRoute:
      enabled: false
    tcpRoute:
      enabled: true
      parentRefs:
        - name: envoy-internal
          namespace: network
          sectionName: ssh
