---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app mosquitto
  namespace: home
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: mosquitto
  values:
    controllers:
      mosquitto:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: public.ecr.aws/docker/library/eclipse-mosquitto
              tag: 2.0.22
            resources:
              requests:
                cpu: 100m
                memory: 250Mi
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: *app
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: ${SVC_MOSQUITTO_ADDR}
        ports:
          mqtt:
            port: 1883

    configMaps:
      config:
        data:
          mosquitto.conf: |-
            allow_anonymous true
            autosave_interval 60
            connection_messages false
            listener 1883
            per_listener_settings false
            persistence true
            persistence_location /config
    persistence:
      config:
        existingClaim: mosquitto
      config-file:
        type: configMap
        identifier: config
        globalMounts:
          - path: /mosquitto/config/mosquitto.conf
            subPath: mosquitto.conf
