---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: ntfy
spec:
  type: generic
  address: http://ntfy-bridge.flux-system.svc.cluster.local:8080/
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: ntfy-alert
spec:
  providerRef:
    name: ntfy
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: '*'
  exclusionList:
    - ".*Dependencies do not meet ready condition.*"
    - ".*Reconciliation finished in .*$"
    - ".*OCIRepository/.*configured.*"
