---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo-runner
spec:
  chartRef:
    kind: OCIRepository
    name: forgejo-runner
  interval: 1h
  values:
    controllers:
      forgejo-runner:
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: code.forgejo.org/forgejo/runner
              tag: 3.5.0
            env:
              FORGEJO_INSTANCE_URL: "https://git.${SECRET_DOMAIN}"
              # Token is pulled from ExternalSecret
              FORGEJO_RUNNER_REGISTRATION_TOKEN:
                secretKeyRef:
                  name: forgejo-secret
                  key: RUNNER_TOKEN
              DOCKER_HOST: tcp://localhost:2375
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 256Mi
          dind:
            image:
              repository: docker
              tag: 26-dind
            env:
              DOCKER_TLS_CERTDIR: ""
            securityContext:
              privileged: true
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 1Gi
    defaultPodOptions:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
    persistence:
      data:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 5Gi
        globalMounts:
          - path: /data
