---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: three14
  namespace: three14
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: three14
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: "docker.io/library/nginx"
              tag: 1.29.8

            resources:
              requests:
                cpu: 100m
                memory: 100Mi
              limits:
                memory: 500Mi
    service:
      app:
        ports:
          http:
            port: &port 80
    route:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/description: three14
          gethomepage.dev/group: sites
          gethomepage.dev/name: three14
          gethomepage.dev/app: three14
        hostnames:
          - three14.${SECRET_DOMAIN}
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
                port: *port

    persistence:
      config:
        type: nfs
        server: prox.${SECRET_OG_DOMAIN}
        path: /saspool1/sites/three14creations
        globalMounts:
          - path: /usr/share/nginx/html
