---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app external-dns-technitium
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 1h
  target:
    name: *app
    template:
      data:
        tsig_key: "{{ .tsig_key }}"
  dataFrom:
  - extract:
      key: *app
