---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app technitium-dns-companion
spec:
  interval: 1h
  path: ./kubernetes/apps/network/technitium-dns-companion/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: network
  wait: false
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/kopiur/backup
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
    substitute:
      APP: *app
